### PR TITLE
make css important in case theme or snippet overwrites

### PR DESCRIPTION
**Pull request by webcubed**

### CODE REVIEW

**Comment by L3-N0X** [comment]
Thanks for the PR! Does this fix anything with the comfy theme (#17 or #18)? Or is this just 'in case' there will be overwrites?

**Comment by webcubed** [comment]
I'm not sure, still testing. It theoretically should work but for now, it looks like this just makes the css not apply 😭 
image
it's supposed to fix this, should've tested before opening pr.

**Comment by webcubed** [comment]
image
this monstrosity

**Comment by webcubed** [comment]
happens because other themes overwrite the grid template
image

**Comment by webcubed** [comment]
adding !important works but my implementation seems to be breaking it.

**Comment by webcubed** [comment]
image
Alright i think it's good

**Comment by webcubed** [comment]
> Thanks for the PR! Does this fix anything with the comfy theme (#17 or #18)? Or is this just 'in case' there will be overwrites?

This was tested on the comfy theme and it will apply "in case", so it should fix the problem entirely

**Comment by webcubed** [comment]
This existing css might/will conflict with the extension that shows the playlists that a certain song is in 
image
but only when not fullscreened

**Comment by L3-N0X** [comment]
Yeah just tested it too, works like a charm! 
I was wondering if it may even be possible to just "add" a column and keeping the default formatting because the left spacing is not the same with comfy UI now because the whole css gets replaced with the css in this code, replacing any changes made by themes. But I guess this is not too important, so i'll be merging this!
The conflict with other extensions is a known problem, it sometimes gets fixed when zooming out, but I can't gurantee that this extension works together fine with every other extension out there

**Pull request merged**
